### PR TITLE
Create configuration file

### PR DESCRIPTION
**Pull request by Ava-S**
Major release since we use config file now to read Semantic Header, Dataset description and to create connection to database

### CODE REVIEW

**Review by freekatvdbergdotus — APPROVED** [review]

**Review by freekatvdbergdotus — APPROVED** [review]

**Review by freekatvdbergdotus — APPROVED** [review]

**Review by freekatvdbergdotus — APPROVED** [review]

**Review by freekatvdbergdotus — APPROVED** [review]

**Review by freekatvdbergdotus — APPROVED** [review]

**Review by freekatvdbergdotus — COMMENTED** [review]
At db_connection.py line 121, would it be possible to make a DatabaseConnection so that it accepts a config only and derives what it needs from the config?

**Comment by Ava-S** [comment]
> At db_connection.py line 121, would it be possible to make a DatabaseConnection so that it accepts a config only and derives what it needs from the config? Or make a hierarchy of configurations?

Do you mean that we remove the functions at line 111 and line 125 (set_up_connection, set_up_connection_using_key) and that we use only the config file? --> Yes, that's desirable,

**Comment by Ava-S** [comment]
> At db_connection.py line 121, would it be possible to make a DatabaseConnection so that it accepts a config only and derives what it needs from the config? Or make a hierarchy of configurations?

Do you mean that we remove the functions at line 111 and line 125 (set_up_connection, set_up_connection_using_key) and that we use only the config file? --> Yes, see new commit!

**Review by freekatvdbergdotus — COMMENTED** [review]
Looks more elegant to me!

**Pull request merged**
